name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: brunohenriqueruas
          password: 0b836632-0806-4b11-bceb-bf5ed46b958e
                
   


      -
        name: Build and push
        uses: docker/build-push-action@v2
      - name: docker login
        run: | # log into docker hub account
          docker login -u username -p password
      - name: Get current date # get the date of the build
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag $username/:${{ steps.date.outputs.date }}
      - name: Docker Push
        run: docker push $DOCKER_USER/brunohenriqueruas/build:${{ steps.date.outputs.date }}
